apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0-rc-jammy
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: docker-entry
        volumes:
          - name: docker-entry
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              name: mongo-secrets
        ports:
        - containerPort: 27017
      volumes:
        - name: docker-entry
      livenessProbe:
                exec:
                  command:
                    - mongo
                    - --disableImplicitSessions
                    - --eval
                    - "db.adminCommand('ping')"
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5
                successThreshold: 1
                failureThreshold: 6
      readinessProbe:
                exec:
                  command:
                    - mongo
                    - --disableImplicitSessions
                    - --eval
                    - "db.adminCommand('ping')"
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5
                successThreshold: 1
                failureThreshold: 6