apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0-rc-jammy
          ports:
            - containerPort: 27017
              hostPort: 27017
          volumeMounts:
            - name: docker-entry
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password123
            - name: MONGO_INITDB_ROOT_PASSWOsRD
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongo-secrets
      volumes:
        - name: docker-entry
          configMap:
            name: mongo-init
          