apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
spec:
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      labels:
        app: temporal-server
    spec:
      containers:
      - name: temporal-server
        image: temporalio/server
        ports:
        - containerPort: 7233
