apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-vc
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /postgres-data/pg-data
