apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  username: YWRtaW4=  # 'admin' 
  password: c3VwZXItc2VjcmV0LXBhc3N3b3Jk    # 'super-secret-password'

  # Not so secret... :O